# Change these first
owner: gnosischain
repo: gnosispay-uptime
sites:
  - name: "Testnet RPC"
    method: POST
    url: https://rpc.bicoccachain.net/
    headers: ["Content-Type: application/json"]
    body: |
      {
        "method": "eth_blockNumber",
        "params":[],
        "id":1,
        "jsonrpc":"2.0"
      }
  - name: "Testnet Blockscout Explorer"
    url: https://blockscout.bicoccachain.net/
status-website:
  name: GnosisPay
  introTitle: "**GnosisPay**"
  introMessage: Check the availability for GnosisPay services
  cname: status.gnosispay.com
  theme: dark

