# Change these first
owner: gnosischain
repo: gnosispay-uptime
sites:
  - name: "GnosisPay"
    url: https://gnosispay.com/
  - name: "GnosisPay DEVNET RPC"
    method: POST
    url: https://rpc.devnet.gnosispay.network
    headers: ["Content-Type: application/json"]
    body: |
      {
        "method": "eth_blockNumber",
        "params":[],
        "id":1,
        "jsonrpc":"2.0"
      }
  - name: "GnosisPay DEVNET Explorer"
    url: https://explorer.devnet.gnosispay.network
  - name: "GnosisPay TESTNET RPC"
    method: POST
    url: https://rpc.testnet.gnosispay.network
    headers: ["Content-Type: application/json"]
    body: |
      {
        "method": "eth_blockNumber",
        "params":[],
        "id":1,
        "jsonrpc":"2.0"
      }
  - name: "GnosisPay TESTNET Explorer"
    url: https://explorer.testnet.gnosispay.network
  - name: "Bicocca Testnet RPC"
    method: POST
    url: https://rpc.bicoccachain.net/
    headers: ["Content-Type: application/json"]
    body: |
      {
        "method": "eth_blockNumber",
        "params":[],
        "id":1,
        "jsonrpc":"2.0"
      }
  - name: "Bicocca Testnet Blockscout Explorer"
    url: https://explorer.bicoccachain.net/
status-website:
  name: GnosisPay
  introTitle: "**GnosisPay**"
  introMessage: Check the availability for GnosisPay services
  cname: status.gnosispay.com
  theme: dark

